//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SealingSchoolWPF.Resources.Language {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SealingSchoolWPF.Resources.Language.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Über ähnelt.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Buchhaltung ähnelt.
        /// </summary>
        public static string Accounting {
            get {
                return ResourceManager.GetString("Accounting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kontonummer ähnelt.
        /// </summary>
        public static string AccountNoLong {
            get {
                return ResourceManager.GetString("AccountNoLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die KTO ähnelt.
        /// </summary>
        public static string AccountNoShort {
            get {
                return ResourceManager.GetString("AccountNoShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Konto Inhaber ähnelt.
        /// </summary>
        public static string AccountOwnerLong {
            get {
                return ResourceManager.GetString("AccountOwnerLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kto. Inh. ähnelt.
        /// </summary>
        public static string AccountOwnerShort {
            get {
                return ResourceManager.GetString("AccountOwnerShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Informationen ähnelt.
        /// </summary>
        public static string AdditionalInfo {
            get {
                return ResourceManager.GetString("AdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Admin Email ähnelt.
        /// </summary>
        public static string AdminMail {
            get {
                return ResourceManager.GetString("AdminMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Adresse ähnelt.
        /// </summary>
        public static string Adress {
            get {
                return ResourceManager.GetString("Adress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aussehen ähnelt.
        /// </summary>
        public static string Appereance {
            get {
                return ResourceManager.GetString("Appereance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bankdaten ähnelt.
        /// </summary>
        public static string Bankdata {
            get {
                return ResourceManager.GetString("Bankdata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bankname ähnelt.
        /// </summary>
        public static string BankName {
            get {
                return ResourceManager.GetString("BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bankleitzahl ähnelt.
        /// </summary>
        public static string BankNoLong {
            get {
                return ResourceManager.GetString("BankNoLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die BLZ ähnelt.
        /// </summary>
        public static string BankNoShort {
            get {
                return ResourceManager.GetString("BankNoShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Basis ähnelt.
        /// </summary>
        public static string Base {
            get {
                return ResourceManager.GetString("Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die BIC ähnelt.
        /// </summary>
        public static string Bic {
            get {
                return ResourceManager.GetString("Bic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Boot ähnelt.
        /// </summary>
        public static string Boat {
            get {
                return ResourceManager.GetString("Boat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Boot Typ ähnelt.
        /// </summary>
        public static string BoatTyp {
            get {
                return ResourceManager.GetString("BoatTyp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Buchungen ähnelt.
        /// </summary>
        public static string Bookings {
            get {
                return ResourceManager.GetString("Bookings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Marke ähnelt.
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kalender ähnelt.
        /// </summary>
        public static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kapazität ähnelt.
        /// </summary>
        public static string Capacity {
            get {
                return ResourceManager.GetString("Capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stadt ähnelt.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rückgängig ähnelt.
        /// </summary>
        public static string Clear_ToolTip {
            get {
                return ResourceManager.GetString("Clear_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alle Felder leeren ähnelt.
        /// </summary>
        public static string Clear_ToolTip_Desc {
            get {
                return ResourceManager.GetString("Clear_ToolTip_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Land ähnelt.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kurs ähnelt.
        /// </summary>
        public static string Course {
            get {
                return ResourceManager.GetString("Course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kursende ähnelt.
        /// </summary>
        public static string CourseEnd {
            get {
                return ResourceManager.GetString("CourseEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte wählen Sie Start- und Enddatum aus ähnelt.
        /// </summary>
        public static string CoursePlanDateDescription {
            get {
                return ResourceManager.GetString("CoursePlanDateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kursplanung ähnelt.
        /// </summary>
        public static string CoursePlanning {
            get {
                return ResourceManager.GetString("CoursePlanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kurse ähnelt.
        /// </summary>
        public static string Courses {
            get {
                return ResourceManager.GetString("Courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kursstart ähnelt.
        /// </summary>
        public static string CourseStart {
            get {
                return ResourceManager.GetString("CourseStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kursstatus ähnelt.
        /// </summary>
        public static string CourseStatus {
            get {
                return ResourceManager.GetString("CourseStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte wählen Sie den Kursstatus aus ähnelt.
        /// </summary>
        public static string CourseStatusDescription {
            get {
                return ResourceManager.GetString("CourseStatusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erstellen ähnelt.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erstellen ähnelt.
        /// </summary>
        public static string Create_ToolTip {
            get {
                return ResourceManager.GetString("Create_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neuen Datensatz erstellen ähnelt.
        /// </summary>
        public static string Create_ToolTip_Desc {
            get {
                return ResourceManager.GetString("Create_ToolTip_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anmeldungen durchführen ähnelt.
        /// </summary>
        public static string CreateRegistration {
            get {
                return ResourceManager.GetString("CreateRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gutschrift ähnelt.
        /// </summary>
        public static string CreditNote {
            get {
                return ResourceManager.GetString("CreditNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gutschriften ähnelt.
        /// </summary>
        public static string CreditNotes {
            get {
                return ResourceManager.GetString("CreditNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Crew Anzahl ähnelt.
        /// </summary>
        public static string CrewAmount {
            get {
                return ResourceManager.GetString("CrewAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Währung ähnelt.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tagessatz ähnelt.
        /// </summary>
        public static string DailyFee {
            get {
                return ResourceManager.GetString("DailyFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Löschen ähnelt.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Löschen ähnelt.
        /// </summary>
        public static string Delete_ToolTip {
            get {
                return ResourceManager.GetString("Delete_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ausgewählten Datensatz löschen ähnelt.
        /// </summary>
        public static string Delete_ToolTip_Desc {
            get {
                return ResourceManager.GetString("Delete_ToolTip_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beschreibung ähnelt.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Details ähnelt.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Details ähnelt.
        /// </summary>
        public static string Details_ToolTip {
            get {
                return ResourceManager.GetString("Details_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ausgewählten Datensatz anzeigen ähnelt.
        /// </summary>
        public static string Details_ToolTip_Desc {
            get {
                return ResourceManager.GetString("Details_ToolTip_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dokument ähnelt.
        /// </summary>
        public static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dokumente ähnelt.
        /// </summary>
        public static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DSV ähnelt.
        /// </summary>
        public static string DSV {
            get {
                return ResourceManager.GetString("DSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dauer ähnelt.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bearbeiten ähnelt.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bearbeiten ähnelt.
        /// </summary>
        public static string Edit_ToolTip {
            get {
                return ResourceManager.GetString("Edit_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ausgewählten Datensatz bearbeiten ähnelt.
        /// </summary>
        public static string Edit_ToolTip_Desc {
            get {
                return ResourceManager.GetString("Edit_ToolTip_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email ähnelt.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ende ähnelt.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte wählen Sie das Enddatum aus ähnelt.
        /// </summary>
        public static string EndDateDescription {
            get {
                return ResourceManager.GetString("EndDateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ext. Bezeichnung ähnelt.
        /// </summary>
        public static string extLabel {
            get {
                return ResourceManager.GetString("extLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fax 1 ähnelt.
        /// </summary>
        public static string Fax1 {
            get {
                return ResourceManager.GetString("Fax1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fax 2 ähnelt.
        /// </summary>
        public static string Fax2 {
            get {
                return ResourceManager.GetString("Fax2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Honorar ähnelt.
        /// </summary>
        public static string Fee {
            get {
                return ResourceManager.GetString("Fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorname ähnelt.
        /// </summary>
        public static string Firstname {
            get {
                return ResourceManager.GetString("Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schriftgröße ähnelt.
        /// </summary>
        public static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bruttopreis ähnelt.
        /// </summary>
        public static string GrossPrice {
            get {
                return ResourceManager.GetString("GrossPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gruppe ähnelt.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stundensatz ähnelt.
        /// </summary>
        public static string HourlyFee {
            get {
                return ResourceManager.GetString("HourlyFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IBAN ähnelt.
        /// </summary>
        public static string Iban {
            get {
                return ResourceManager.GetString("Iban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kennung ähnelt.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kursleiter ähnelt.
        /// </summary>
        public static string Instructor {
            get {
                return ResourceManager.GetString("Instructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anz. Kursleiter ähnelt.
        /// </summary>
        public static string InstructorCount {
            get {
                return ResourceManager.GetString("InstructorCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rechnung ähnelt.
        /// </summary>
        public static string Invoice {
            get {
                return ResourceManager.GetString("Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rechnungsdatum ähnelt.
        /// </summary>
        public static string InvoiceDate {
            get {
                return ResourceManager.GetString("InvoiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rechnungen ähnelt.
        /// </summary>
        public static string Invoices {
            get {
                return ResourceManager.GetString("Invoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rechnungsstatus ähnelt.
        /// </summary>
        public static string InvoiceStatus {
            get {
                return ResourceManager.GetString("InvoiceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bezeichnung ähnelt.
        /// </summary>
        public static string Label {
            get {
                return ResourceManager.GetString("Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nachname ähnelt.
        /// </summary>
        public static string Lastname {
            get {
                return ResourceManager.GetString("Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rettungsschwimmer ähnelt.
        /// </summary>
        public static string LifeGuard {
            get {
                return ResourceManager.GetString("LifeGuard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mandant ähnelt.
        /// </summary>
        public static string Mandant {
            get {
                return ResourceManager.GetString("Mandant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stammdaten ähnelt.
        /// </summary>
        public static string MasterData {
            get {
                return ResourceManager.GetString("MasterData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Material ähnelt.
        /// </summary>
        public static string Material {
            get {
                return ResourceManager.GetString("Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Materialgruppe ähnelt.
        /// </summary>
        public static string MaterialGroup {
            get {
                return ResourceManager.GetString("MaterialGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Materialname ähnelt.
        /// </summary>
        public static string MaterialName {
            get {
                return ResourceManager.GetString("MaterialName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Materialstatus ähnelt.
        /// </summary>
        public static string MaterialStatus {
            get {
                return ResourceManager.GetString("MaterialStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Materialart ähnelt.
        /// </summary>
        public static string MaterialType {
            get {
                return ResourceManager.GetString("MaterialType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die USt. ähnelt.
        /// </summary>
        public static string NetAmount {
            get {
                return ResourceManager.GetString("NetAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nettopreis ähnelt.
        /// </summary>
        public static string NetPrice {
            get {
                return ResourceManager.GetString("NetPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neuigkeiten ähnelt.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nummer ähnelt.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nr. ähnelt.
        /// </summary>
        public static string NoShort {
            get {
                return ResourceManager.GetString("NoShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Notizen ähnelt.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Angebot ähnelt.
        /// </summary>
        public static string Offering {
            get {
                return ResourceManager.GetString("Offering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Angebote ähnelt.
        /// </summary>
        public static string Offerings {
            get {
                return ResourceManager.GetString("Offerings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Übersicht ähnelt.
        /// </summary>
        public static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zahlstatus ähnelt.
        /// </summary>
        public static string PaymentStatus {
            get {
                return ResourceManager.GetString("PaymentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zahlungszieldatum ähnelt.
        /// </summary>
        public static string PaymentTargetDate {
            get {
                return ResourceManager.GetString("PaymentTargetDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Postleitzahl ähnelt.
        /// </summary>
        public static string PostalLong {
            get {
                return ResourceManager.GetString("PostalLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PLZ ähnelt.
        /// </summary>
        public static string PostalShort {
            get {
                return ResourceManager.GetString("PostalShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preis ähnelt.
        /// </summary>
        public static string Pricing {
            get {
                return ResourceManager.GetString("Pricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Qualifikation ähnelt.
        /// </summary>
        public static string Qualification {
            get {
                return ResourceManager.GetString("Qualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Qualifikationen ähnelt.
        /// </summary>
        public static string Qualifications {
            get {
                return ResourceManager.GetString("Qualifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string QualiLong {
            get {
                return ResourceManager.GetString("QualiLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abkürzung ähnelt.
        /// </summary>
        public static string QualiShort {
            get {
                return ResourceManager.GetString("QualiShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bewertung ähnelt.
        /// </summary>
        public static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bewertungen ähnelt.
        /// </summary>
        public static string Ratings {
            get {
                return ResourceManager.GetString("Ratings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Referenz ähnelt.
        /// </summary>
        public static string Reference {
            get {
                return ResourceManager.GetString("Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Referenzen ähnelt.
        /// </summary>
        public static string References {
            get {
                return ResourceManager.GetString("References", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aktualisieren ähnelt.
        /// </summary>
        public static string Refresh_ToolTip {
            get {
                return ResourceManager.GetString("Refresh_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aktuelle Ansicht neu laden ähnelt.
        /// </summary>
        public static string Refresh_ToolTip_Desc {
            get {
                return ResourceManager.GetString("Refresh_ToolTip_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anmeldung ähnelt.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anmeldungen ähnelt.
        /// </summary>
        public static string Registrations {
            get {
                return ResourceManager.GetString("Registrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reparatur ähnelt.
        /// </summary>
        public static string Repair {
            get {
                return ResourceManager.GetString("Repair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reparaturvermerk ähnelt.
        /// </summary>
        public static string RepairAction {
            get {
                return ResourceManager.GetString("RepairAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zeile 1 ähnelt.
        /// </summary>
        public static string Row1 {
            get {
                return ResourceManager.GetString("Row1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zeile 2 ähnelt.
        /// </summary>
        public static string Row2 {
            get {
                return ResourceManager.GetString("Row2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zeile 3 ähnelt.
        /// </summary>
        public static string Row3 {
            get {
                return ResourceManager.GetString("Row3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speichern ähnelt.
        /// </summary>
        public static string Save_ToolTip {
            get {
                return ResourceManager.GetString("Save_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ausgewählten Datensatz speichern ähnelt.
        /// </summary>
        public static string Save_ToolTip_Desc {
            get {
                return ResourceManager.GetString("Save_ToolTip_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ausgewählten Datensatz speichern und Eingabemaske schliessen ähnelt.
        /// </summary>
        public static string SaveClose_ToolTip_Desc {
            get {
                return ResourceManager.GetString("SaveClose_ToolTip_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speichern und Neu ähnelt.
        /// </summary>
        public static string SaveNext_ToolTip_Desc {
            get {
                return ResourceManager.GetString("SaveNext_ToolTip_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SBF Binnen ähnelt.
        /// </summary>
        public static string SBFBINNEN {
            get {
                return ResourceManager.GetString("SBFBINNEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SBF See ähnelt.
        /// </summary>
        public static string SBFSEA {
            get {
                return ResourceManager.GetString("SBFSEA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kurs auswählen ähnelt.
        /// </summary>
        public static string SelectCourse {
            get {
                return ResourceManager.GetString("SelectCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte wählen Sie den Kurs aus. ähnelt.
        /// </summary>
        public static string SelectCourseDescription {
            get {
                return ResourceManager.GetString("SelectCourseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Endtdatum auswählen ähnelt.
        /// </summary>
        public static string SelectEnd {
            get {
                return ResourceManager.GetString("SelectEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kursleiter auswählen ähnelt.
        /// </summary>
        public static string SelectInstructor {
            get {
                return ResourceManager.GetString("SelectInstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Startdatum auswählen ähnelt.
        /// </summary>
        public static string SelectStart {
            get {
                return ResourceManager.GetString("SelectStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte Teilnehmer auswählen ähnelt.
        /// </summary>
        public static string SelectStudent {
            get {
                return ResourceManager.GetString("SelectStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sepa-Mandat ähnelt.
        /// </summary>
        public static string Sepa {
            get {
                return ResourceManager.GetString("Sepa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Seriennummer ähnelt.
        /// </summary>
        public static string SerialNumber {
            get {
                return ResourceManager.GetString("SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen ähnelt.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SHS ähnelt.
        /// </summary>
        public static string SHS {
            get {
                return ResourceManager.GetString("SHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SKS ähnelt.
        /// </summary>
        public static string SKS {
            get {
                return ResourceManager.GetString("SKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Software ähnelt.
        /// </summary>
        public static string Software {
            get {
                return ResourceManager.GetString("Software", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spezifisch 1 ähnelt.
        /// </summary>
        public static string Spezify1 {
            get {
                return ResourceManager.GetString("Spezify1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spezifisch 2 ähnelt.
        /// </summary>
        public static string Spezify2 {
            get {
                return ResourceManager.GetString("Spezify2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SRC ähnelt.
        /// </summary>
        public static string SRC {
            get {
                return ResourceManager.GetString("SRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SSS ähnelt.
        /// </summary>
        public static string SSS {
            get {
                return ResourceManager.GetString("SSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start ähnelt.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte wählen Sie das Startdatum aus ähnelt.
        /// </summary>
        public static string StartDateDescription {
            get {
                return ResourceManager.GetString("StartDateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Straße ähnelt.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Teilnehmer ähnelt.
        /// </summary>
        public static string Students {
            get {
                return ResourceManager.GetString("Students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zusammenfassung ähnelt.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hier sehen Sie eine Zusammenfassung ähnelt.
        /// </summary>
        public static string SummaryDescription {
            get {
                return ResourceManager.GetString("SummaryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Swift ähnelt.
        /// </summary>
        public static string Swift {
            get {
                return ResourceManager.GetString("Swift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tel 1 ähnelt.
        /// </summary>
        public static string Tel1 {
            get {
                return ResourceManager.GetString("Tel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tel 2 ähnelt.
        /// </summary>
        public static string Tel2 {
            get {
                return ResourceManager.GetString("Tel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorlage ähnelt.
        /// </summary>
        public static string Template {
            get {
                return ResourceManager.GetString("Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Test ähnelt.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zeiten ähnelt.
        /// </summary>
        public static string Times {
            get {
                return ResourceManager.GetString("Times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anmeldung ähnelt.
        /// </summary>
        public static string TrainingActivity {
            get {
                return ResourceManager.GetString("TrainingActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die UBI ähnelt.
        /// </summary>
        public static string UBI {
            get {
                return ResourceManager.GetString("UBI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datensatz aktualisieren ähnelt.
        /// </summary>
        public static string Update_ToolTip_Desc {
            get {
                return ResourceManager.GetString("Update_ToolTip_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die USt ähnelt.
        /// </summary>
        public static string Ust {
            get {
                return ResourceManager.GetString("Ust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die VAT ID ähnelt.
        /// </summary>
        public static string UstId {
            get {
                return ResourceManager.GetString("UstId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Webseite ähnelt.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Willkommen ähnelt.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
